import { Verse } from '../types';

export const KJV_LIBRARY: Verse[] = [
  { book: 'Genesis', chapter: 1, verse: 1, text: 'In the beginning God created the heaven and the earth.' },
  { book: 'Genesis', chapter: 1, verse: 27, text: 'So God created man in his own image, in the image of God created he him; male and female created he them.' },
  { book: 'Exodus', chapter: 20, verse: 3, text: 'Thou shalt have no other gods before me.' },
  { book: 'Exodus', chapter: 20, verse: 12, text: 'Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee.' },
  { book: 'Numbers', chapter: 6, verse: 24, text: 'The LORD bless thee, and keep thee:' },
  { book: 'Numbers', chapter: 6, verse: 25, text: 'The LORD make his face shine upon thee, and be gracious unto thee:' },
  { book: 'Deuteronomy', chapter: 6, verse: 5, text: 'And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.' },
  { book: 'Joshua', chapter: 1, verse: 9, text: 'Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.' },
  { book: 'Joshua', chapter: 24, verse: 15, text: 'And if it seem evil unto you to serve the LORD, choose you this day whom ye will serve; whether the gods which your fathers served that were on the other side of the flood, or the gods of the Amorites, in whose land ye dwell: but as for me and my house, we will serve the LORD.' },
  { book: '1 Samuel', chapter: 16, verse: 7, text: 'But the LORD said unto Samuel, Look not on his countenance, or on the height of his stature; because I have refused him: for the LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart.' },
  { book: 'Psalm', chapter: 1, verse: 1, text: 'Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful.' },
  { book: 'Psalm', chapter: 19, verse: 1, text: 'The heavens declare the glory of God; and the firmament sheweth his handywork.' },
  { book: 'Psalm', chapter: 23, verse: 1, text: 'The LORD is my shepherd; I shall not want.' },
  { book: 'Psalm', chapter: 23, verse: 4, text: 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.' },
  { book: 'Psalm', chapter: 27, verse: 1, text: 'The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?' },
  { book: 'Psalm', chapter: 34, verse: 8, text: 'O taste and see that the LORD is good: blessed is the man that trusteth in him.' },
  { book: 'Psalm', chapter: 37, verse: 4, text: 'Delight thyself also in the LORD; and he shall give thee the desires of thine heart.' },
  { book: 'Psalm', chapter: 46, verse: 1, text: 'God is our refuge and strength, a very present help in trouble.' },
  { book: 'Psalm', chapter: 46, verse: 10, text: 'Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.' },
  { book: 'Psalm', chapter: 51, verse: 10, text: 'Create in me a clean heart, O God; and renew a right spirit within me.' },
  { book: 'Psalm', chapter: 100, verse: 1, text: 'Make a joyful noise unto the LORD, all ye lands.' },
  { book: 'Psalm', chapter: 118, verse: 24, text: 'This is the day which the LORD hath made; we will rejoice and be glad in it.' },
  { book: 'Psalm', chapter: 119, verse: 11, text: 'Thy word have I hid in mine heart, that I might not sin against thee.' },
  { book: 'Psalm', chapter: 119, verse: 105, text: 'Thy word is a lamp unto my feet, and a light unto my path.' },
  { book: 'Psalm', chapter: 121, verse: 1, text: 'I will lift up mine eyes unto the hills, from whence cometh my help.' },
  { book: 'Psalm', chapter: 139, verse: 14, text: 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.' },
  { book: 'Proverbs', chapter: 3, verse: 5, text: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.' },
  { book: 'Proverbs', chapter: 3, verse: 6, text: 'In all thy ways acknowledge him, and he shall direct thy paths.' },
  { book: 'Proverbs', chapter: 15, verse: 1, text: 'A soft answer turneth away wrath: but grievous words stir up anger.' },
  { book: 'Proverbs', chapter: 18, verse: 10, text: 'The name of the LORD is a strong tower: the righteous runneth into it, and is safe.' },
  { book: 'Isaiah', chapter: 9, verse: 6, text: 'For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.' },
  { book: 'Isaiah', chapter: 40, verse: 31, text: 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.' },
  { book: 'Isaiah', chapter: 41, verse: 10, text: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.' },
  { book: 'Jeremiah', chapter: 29, verse: 11, text: 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.' },
  { book: 'Jeremiah', chapter: 33, verse: 3, text: 'Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.' },
  { book: 'Lamentations', chapter: 3, verse: 22, text: 'It is of the LORD\'s mercies that we are not consumed, because his compassions fail not.' },
  { book: 'Lamentations', chapter: 3, verse: 23, text: 'They are new every morning: great is thy faithfulness.' },
  { book: 'Micah', chapter: 6, verse: 8, text: 'He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?' },
  { book: 'Matthew', chapter: 5, verse: 14, text: 'Ye are the light of the world. A city that is set on an hill cannot be hid.' },
  { book: 'Matthew', chapter: 5, verse: 16, text: 'Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.' },
  { book: 'Matthew', chapter: 6, verse: 33, text: 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.' },
  { book: 'Matthew', chapter: 7, verse: 7, text: 'Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:' },
  { book: 'Matthew', chapter: 11, verse: 28, text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.' },
  { book: 'Matthew', chapter: 19, verse: 26, text: 'But Jesus beheld them, and said unto them, With men this is impossible; but with God all things are possible.' },
  { book: 'Matthew', chapter: 22, verse: 37, text: 'Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind.' },
  { book: 'Matthew', chapter: 28, verse: 19, text: 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:' },
  { book: 'Matthew', chapter: 28, verse: 20, text: 'Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen.' },
  { book: 'Mark', chapter: 10, verse: 27, text: 'And Jesus looking upon them saith, With men it is impossible, but not with God: for with God all things are possible.' },
  { book: 'Mark', chapter: 12, verse: 30, text: 'And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment.' },
  { book: 'Luke', chapter: 1, verse: 37, text: 'For with God nothing shall be impossible.' },
  { book: 'Luke', chapter: 2, verse: 10, text: 'And the angel said unto them, Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people.' },
  { book: 'Luke', chapter: 2, verse: 11, text: 'For unto you is born this day in the city of David a Saviour, which is Christ the Lord.' },
  { book: 'Luke', chapter: 6, verse: 31, text: 'And as ye would that men should do to you, do ye also to them likewise.' },
  { book: 'John', chapter: 1, verse: 1, text: 'In the beginning was the Word, and the Word was with God, and the Word was God.' },
  { book: 'John', chapter: 1, verse: 12, text: 'But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:' },
  { book: 'John', chapter: 3, verse: 16, text: 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.' },
  { book: 'John', chapter: 3, verse: 17, text: 'For God sent not his Son into the world to condemn the world; but that the world through him might be saved.' },
  { book: 'John', chapter: 8, verse: 12, text: 'Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.' },
  { book: 'John', chapter: 8, verse: 32, text: 'And ye shall know the truth, and the truth shall make you free.' },
  { book: 'John', chapter: 10, verse: 10, text: 'The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.' },
  { book: 'John', chapter: 11, verse: 25, text: 'Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live:' },
  { book: 'John', chapter: 13, verse: 34, text: 'A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.' },
  { book: 'John', chapter: 13, verse: 35, text: 'By this shall all men know that ye are my disciples, if ye have love one to another.' },
  { book: 'John', chapter: 14, verse: 1, text: 'Let not your heart be troubled: ye believe in God, believe also in me.' },
  { book: 'John', chapter: 14, verse: 6, text: 'Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.' },
  { book: 'John', chapter: 14, verse: 15, text: 'If ye love me, keep my commandments.' },
  { book: 'John', chapter: 14, verse: 27, text: 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.' },
  { book: 'John', chapter: 15, verse: 5, text: 'I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.' },
  { book: 'John', chapter: 15, verse: 13, text: 'Greater love hath no man than this, that a man lay down his life for his friends.' },
  { book: 'Acts', chapter: 1, verse: 8, text: 'But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth.' },
  { book: 'Acts', chapter: 4, verse: 12, text: 'Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.' },
  { book: 'Acts', chapter: 16, verse: 31, text: 'And they said, Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house.' },
  { book: 'Romans', chapter: 1, verse: 16, text: 'For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth; to the Jew first, and also to the Greek.' },
  { book: 'Romans', chapter: 3, verse: 23, text: 'For all have sinned, and come short of the glory of God;' },
  { book: 'Romans', chapter: 5, verse: 8, text: 'But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.' },
  { book: 'Romans', chapter: 6, verse: 23, text: 'For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.' },
  { book: 'Romans', chapter: 8, verse: 1, text: 'There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.' },
  { book: 'Romans', chapter: 8, verse: 28, text: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.' },
  { book: 'Romans', chapter: 8, verse: 31, text: 'What shall we then say to these things? If God be for us, who can be against us?' },
  { book: 'Romans', chapter: 8, verse: 37, text: 'Nay, in all these things we are more than conquerors through him that loved us.' },
  { book: 'Romans', chapter: 8, verse: 38, text: 'For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,' },
  { book: 'Romans', chapter: 8, verse: 39, text: 'Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.' },
  { book: 'Romans', chapter: 10, verse: 9, text: 'That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.' },
  { book: 'Romans', chapter: 10, verse: 10, text: 'For with the heart man believeth unto righteousness; and with the mouth confession is made unto salvation.' },
  { book: 'Romans', chapter: 10, verse: 13, text: 'For whosoever shall call upon the name of the Lord shall be saved.' },
  { book: 'Romans', chapter: 10, verse: 17, text: 'So then faith cometh by hearing, and hearing by the word of God.' },
  { book: 'Romans', chapter: 12, verse: 1, text: 'I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service.' },
  { book: 'Romans', chapter: 12, verse: 2, text: 'And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.' },
  { book: 'Romans', chapter: 12, verse: 21, text: 'Be not overcome of evil, but overcome evil with good.' },
  { book: '1 Corinthians', chapter: 10, verse: 13, text: 'There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it.' },
  { book: '1 Corinthians', chapter: 13, verse: 4, text: 'Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,' },
  { book: '1 Corinthians', chapter: 13, verse: 13, text: 'And now abideth faith, hope, charity, these three; but the greatest of these is charity.' },
  { book: '1 Corinthians', chapter: 16, verse: 14, text: 'Let all your things be done with charity.' },
  { book: '2 Corinthians', chapter: 5, verse: 17, text: 'Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.' },
  { book: '2 Corinthians', chapter: 12, verse: 9, text: 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.' },
  { book: 'Galatians', chapter: 2, verse: 20, text: 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.' },
  { book: 'Galatians', chapter: 5, verse: 22, text: 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,' },
  { book: 'Galatians', chapter: 5, verse: 23, text: 'Meekness, temperance: against such there is no law.' },
  { book: 'Galatians', chapter: 6, verse: 9, text: 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.' },
  { book: 'Ephesians', chapter: 2, verse: 8, text: 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:' },
  { book: 'Ephesians', chapter: 2, verse: 9, text: 'Not of works, lest any man should boast.' },
  { book: 'Ephesians', chapter: 2, verse: 10, text: 'For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.' },
  { book: 'Ephesians', chapter: 4, verse: 32, text: 'And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ\'s sake hath forgiven you.' },
  { book: 'Ephesians', chapter: 6, verse: 10, text: 'Finally, my brethren, be strong in the Lord, and in the power of his might.' },
  { book: 'Ephesians', chapter: 6, verse: 11, text: 'Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.' },
  { book: 'Philippians', chapter: 1, verse: 6, text: 'Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:' },
  { book: 'Philippians', chapter: 4, verse: 4, text: 'Rejoice in the Lord alway: and again I say, Rejoice.' },
  { book: 'Philippians', chapter: 4, verse: 6, text: 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.' },
  { book: 'Philippians', chapter: 4, verse: 7, text: 'And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.' },
  { book: 'Philippians', chapter: 4, verse: 8, text: 'Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.' },
  { book: 'Philippians', chapter: 4, verse: 13, text: 'I can do all things through Christ which strengtheneth me.' },
  { book: 'Philippians', chapter: 4, verse: 19, text: 'But my God shall supply all your need according to his riches in glory by Christ Jesus.' },
  { book: 'Colossians', chapter: 3, verse: 2, text: 'Set your affection on things above, not on things on the earth.' },
  { book: 'Colossians', chapter: 3, verse: 17, text: 'And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him.' },
  { book: 'Colossians', chapter: 3, verse: 23, text: 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men;' },
  { book: '1 Thessalonians', chapter: 5, verse: 16, text: 'Rejoice evermore.' },
  { book: '1 Thessalonians', chapter: 5, verse: 17, text: 'Pray without ceasing.' },
  { book: '1 Thessalonians', chapter: 5, verse: 18, text: 'In every thing give thanks: for this is the will of God in Christ Jesus concerning you.' },
  { book: '2 Timothy', chapter: 1, verse: 7, text: 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.' },
  { book: '2 Timothy', chapter: 3, verse: 16, text: 'All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness:' },
  { book: 'Hebrews', chapter: 4, verse: 12, text: 'For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart.' },
  { book: 'Hebrews', chapter: 11, verse: 1, text: 'Now faith is the substance of things hoped for, the evidence of things not seen.' },
  { book: 'Hebrews', chapter: 11, verse: 6, text: 'But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.' },
  { book: 'Hebrews', chapter: 12, verse: 1, text: 'Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us,' },
  { book: 'Hebrews', chapter: 12, verse: 2, text: 'Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.' },
  { book: 'Hebrews', chapter: 13, verse: 5, text: 'Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee.' },
  { book: 'Hebrews', chapter: 13, verse: 8, text: 'Jesus Christ the same yesterday, and to day, and for ever.' },
  { book: 'James', chapter: 1, verse: 5, text: 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.' },
  { book: 'James', chapter: 1, verse: 17, text: 'Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.' },
  { book: 'James', chapter: 1, verse: 19, text: 'Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath:' },
  { book: 'James', chapter: 1, verse: 22, text: 'But be ye doers of the word, and not hearers only, deceiving your own selves.' },
  { book: 'James', chapter: 4, verse: 7, text: 'Submit yourselves therefore to God. Resist the devil, and he will flee from you.' },
  { book: 'James', chapter: 4, verse: 8, text: 'Draw nigh to God, and he will draw nigh to you. Cleanse your hands, ye sinners; and purify your hearts, ye double minded.' },
  { book: 'James', chapter: 5, verse: 16, text: 'Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.' },
  { book: '1 Peter', chapter: 5, verse: 7, text: 'Casting all your care upon him; for he careth for you.' },
  { book: '2 Peter', chapter: 3, verse: 9, text: 'The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.' },
  { book: '1 John', chapter: 1, verse: 9, text: 'If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.' },
  { book: '1 John', chapter: 3, verse: 1, text: 'Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not.' },
  { book: '1 John', chapter: 3, verse: 18, text: 'My little children, let us not love in word, neither in tongue; but in deed and in truth.' },
  { book: '1 John', chapter: 4, verse: 7, text: 'Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God.' },
  { book: '1 John', chapter: 4, verse: 8, text: 'He that loveth not knoweth not God; for God is love.' },
  { book: '1 John', chapter: 4, verse: 19, text: 'We love him, because he first loved us.' },
  { book: '1 John', chapter: 5, verse: 4, text: 'For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith.' },
  { book: 'Revelation', chapter: 3, verse: 20, text: 'Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me.' },
  { book: 'Revelation', chapter: 21, verse: 4, text: 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.' },
  { book: 'Revelation', chapter: 22, verse: 13, text: 'I am Alpha and Omega, the beginning and the end, the first and the last.' },
  { book: 'Psalm', chapter: 119, verse: 1, text: 'Blessed are the undefiled in the way, who walk in the law of the LORD.' },
  { book: 'Psalm', chapter: 119, verse: 2, text: 'Blessed are they that keep his testimonies, and that seek him with the whole heart.' },
  { book: 'Psalm', chapter: 119, verse: 3, text: 'They also do no iniquity: they walk in his ways.' },
  { book: 'Psalm', chapter: 119, verse: 4, text: 'Thou hast commanded us to keep thy precepts diligently.' },
  { book: 'Psalm', chapter: 119, verse: 5, text: 'O that my ways were directed to keep thy statutes!' },
  { book: 'Psalm', chapter: 119, verse: 6, text: 'Then shall I not be ashamed, when I have respect unto all thy commandments.' },
  { book: 'Psalm', chapter: 119, verse: 7, text: 'I will praise thee with uprightness of heart, when I shall have learned thy righteous judgments.' },
  { book: 'Psalm', chapter: 119, verse: 8, text: 'I will keep thy statutes: O forsake me not utterly.' },
  { book: 'Psalm', chapter: 119, verse: 9, text: 'Wherewithal shall a young man cleanse his way? by taking heed thereto according to thy word.' },
  { book: 'Psalm', chapter: 119, verse: 10, text: 'With my whole heart have I sought thee: O let me not wander from thy commandments.' },
  { book: 'John', chapter: 1, verse: 2, text: 'The same was in the beginning with God.' },
  { book: 'John', chapter: 1, verse: 3, text: 'All things were made by him; and without him was not any thing made that was made.' },
  { book: 'John', chapter: 1, verse: 4, text: 'In him was life; and the life was the light of men.' },
  { book: 'John', chapter: 1, verse: 5, text: 'And the light shineth in darkness; and the darkness comprehended it not.' },
  { book: 'Genesis', chapter: 2, verse: 7, text: 'And the LORD God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.' },
  { book: 'Genesis', chapter: 9, verse: 13, text: 'I do set my bow in the cloud, and it shall be for a token of a covenant between me and the earth.' },
  { book: 'Exodus', chapter: 14, verse: 14, text: 'The LORD shall fight for you, and ye shall hold your peace.' },
  { book: 'Exodus', chapter: 15, verse: 2, text: 'The LORD is my strength and song, and he is become my salvation: he is my God, and I will prepare him an habitation; my father\'s God, and I will exalt him.' },
  { book: 'Leviticus', chapter: 19, verse: 18, text: 'Thou shalt not avenge, nor bear any grudge against the children of thy people, but thou shalt love thy neighbour as thyself: I am the LORD.' },
  { book: 'Numbers', chapter: 23, verse: 19, text: 'God is not a man, that he should lie; neither the son of man, that he should repent: hath he said, and shall he not do it? or hath he spoken, and shall he not make it good?' },
  { book: 'Deuteronomy', chapter: 7, verse: 9, text: 'Know therefore that the LORD thy God, he is God, the faithful God, which keepeth covenant and mercy with them that love him and keep his commandments to a thousand generations;' },
  { book: 'Deuteronomy', chapter: 31, verse: 6, text: 'Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.' },
  { book: 'Joshua', chapter: 1, verse: 8, text: 'This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.' },
  { book: 'Judges', chapter: 5, verse: 31, text: 'So let all thine enemies perish, O LORD: but let them that love him be as the sun when he goeth forth in his might. And the land had rest forty years.' },
  { book: 'Ruth', chapter: 1, verse: 16, text: 'And Ruth said, Intreat me not to leave thee, or to return from following after thee: for whither thou goest, I will go; and where thou lodgest, I will lodge: thy people shall be my people, and thy God my God:' },
  { book: '1 Samuel', chapter: 12, verse: 24, text: 'Only fear the LORD, and serve him in truth with all your heart: for consider how great things he hath done for you.' },
  { book: '2 Samuel', chapter: 22, verse: 31, text: 'As for God, his way is perfect; the word of the LORD is tried: he is a buckler to all them that trust in him.' },
  { book: '1 Kings', chapter: 8, verse: 56, text: 'Blessed be the LORD, that hath given rest unto his people Israel, according to all that he promised: there hath not failed one word of all his good promise, which he promised by the hand of Moses his servant.' },
  { book: '2 Kings', chapter: 19, verse: 19, text: 'Now therefore, O LORD our God, I beseech thee, save thou us out of his hand, that all the kingdoms of the earth may know that thou art the LORD God, even thou only.' },
  { book: '1 Chronicles', chapter: 16, verse: 11, text: 'Seek the LORD and his strength, seek his face continually.' },
  { book: '2 Chronicles', chapter: 7, verse: 14, text: 'If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land.' },
  { book: 'Ezra', chapter: 7, verse: 10, text: 'For Ezra had prepared his heart to seek the law of the LORD, and to do it, and to teach in Israel statutes and judgments.' },
  { book: 'Nehemiah', chapter: 8, verse: 10, text: 'Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.' },
  { book: 'Esther', chapter: 4, verse: 14, text: 'For if thou altogether holdest thy peace at this time, then shall there enlargement and deliverance arise to the Jews from another place; but thou and thy father\'s house shall be destroyed: and who knoweth whether thou art come to the kingdom for such a time as this?' },
  { book: 'Job', chapter: 19, verse: 25, text: 'For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth:' },
  { book: 'Job', chapter: 23, verse: 10, text: 'But he knoweth the way that I take: when he hath tried me, I shall come forth as gold.' },
  { book: 'Psalm', chapter: 16, verse: 11, text: 'Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.' },
  { book: 'Psalm', chapter: 18, verse: 2, text: 'The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower.' },
  { book: 'Psalm', chapter: 32, verse: 8, text: 'I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.' },
  { book: 'Psalm', chapter: 34, verse: 1, text: 'I will bless the LORD at all times: his praise shall continually be in my mouth.' },
  { book: 'Psalm', chapter: 34, verse: 7, text: 'The angel of the LORD encampeth round about them that fear him, and delivereth them.' },
  { book: 'Psalm', chapter: 34, verse: 18, text: 'The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.' },
  { book: 'Psalm', chapter: 37, verse: 5, text: 'Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.' },
  { book: 'Psalm', chapter: 55, verse: 22, text: 'Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.' },
  { book: 'Psalm', chapter: 56, verse: 3, text: 'What time I am afraid, I will trust in thee.' },
  { book: 'Psalm', chapter: 62, verse: 1, text: 'Truly my soul waiteth upon God: from him cometh my salvation.' },
  { book: 'Psalm', chapter: 63, verse: 1, text: 'O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;' },
  { book: 'Psalm', chapter: 73, verse: 26, text: 'My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.' },
  { book: 'Psalm', chapter: 84, verse: 11, text: 'For the LORD God is a sun and shield: the LORD will give grace and glory: no good thing will he withhold from them that walk uprightly.' },
  { book: 'Psalm', chapter: 91, verse: 1, text: 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.' },
  { book: 'Psalm', chapter: 91, verse: 2, text: 'I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust.' },
  { book: 'Psalm', chapter: 91, verse: 11, text: 'For he shall give his angels charge over thee, to keep thee in all thy ways.' },
  { book: 'Psalm', chapter: 103, verse: 1, text: 'Bless the LORD, O my soul: and all that is within me, bless his holy name.' },
  { book: 'Psalm', chapter: 103, verse: 2, text: 'Bless the LORD, O my soul, and forget not all his benefits:' },
];
